services:
  # Skynet Agent application
  skynet-agent:
    build: .
    container_name: skynet-agent
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CHROMA_PATH=/app/data/chroma
      - CHROMA_COLLECTION=skynet_memories
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
